name: Week 2 MLS pipeline

on:
  workflow_dispatch:

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install -r week_2_mls/requirements.txt

      - name: Upload Dataset to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python week_2_mls/model_building/data_register.py


  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install -r week_2_mls/requirements.txt

      - name: Run Data Preparation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python week_2_mls/model_building/prep.py


  model-training:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install -r week_2_mls/requirements.txt

      - name: Model Building
        env:
          HF_TOKEN: ${{ secrets/HF_TOKEN }}
        run: python week_2_mls/model_building/train.py


  deploy-hosting:
    needs: [model-training, data-prep, register-dataset]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: week_2_mls/deployment
          file: week_2_mls/deployment/Dockerfile
          push: false
          tags: my-image-name:latest

      - name: Install Dependencies
        run: pip install -r week_2_mls/requirements.txt

      - name: Push files to Frontend Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets/HF_TOKEN }}
        run: python week_2_mls/hosting/hosting.py
